/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as CuratorRouteImport } from './routes/curator'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as ExitRouteImport } from './routes/exit'
import { Route as ForgottenRouteImport } from './routes/forgotten'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as HallRouteImport } from './routes/hall'
import { Route as KeptRouteImport } from './routes/kept'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LivesRouteImport } from './routes/lives'
import { Route as MapRouteImport } from './routes/map'
import { Route as MidnightRouteImport } from './routes/midnight'
import { Route as NeededRouteImport } from './routes/needed'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as WallRouteImport } from './routes/wall'
import { Route as ArchiveIdRouteImport } from './routes/archive_.$id'
import { Route as LibraryIdRouteImport } from './routes/library_.$id'
import { Route as LivesIdRouteImport } from './routes/lives_.$id'
import { Route as VaultIdRouteImport } from './routes/vault_.$id'
import { Route as VoiceIdRouteImport } from './routes/voice_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const CuratorRoute = CuratorRouteImport.update({
  id: '/curator',
  path: '/curator',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ExitRoute = ExitRouteImport.update({
  id: '/exit',
  path: '/exit',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgottenRoute = ForgottenRouteImport.update({
  id: '/forgotten',
  path: '/forgotten',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const HallRoute = HallRouteImport.update({
  id: '/hall',
  path: '/hall',
  getParentRoute: () => rootRouteImport,
} as any)
const KeptRoute = KeptRouteImport.update({
  id: '/kept',
  path: '/kept',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LivesRoute = LivesRouteImport.update({
  id: '/lives',
  path: '/lives',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MidnightRoute = MidnightRouteImport.update({
  id: '/midnight',
  path: '/midnight',
  getParentRoute: () => rootRouteImport,
} as any)
const NeededRoute = NeededRouteImport.update({
  id: '/needed',
  path: '/needed',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const WallRoute = WallRouteImport.update({
  id: '/wall',
  path: '/wall',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIdRoute = ArchiveIdRouteImport.update({
  id: '/archive_/$id',
  path: '/archive/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIdRoute = LibraryIdRouteImport.update({
  id: '/library_/$id',
  path: '/library/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LivesIdRoute = LivesIdRouteImport.update({
  id: '/lives_/$id',
  path: '/lives/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultIdRoute = VaultIdRouteImport.update({
  id: '/vault_/$id',
  path: '/vault/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceIdRoute = VoiceIdRouteImport.update({
  id: '/voice_/$id',
  path: '/voice/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/curator': typeof CuratorRoute
  '/desk': typeof DeskRoute
  '/exit': typeof ExitRoute
  '/forgotten': typeof ForgottenRoute
  '/guidelines': typeof GuidelinesRoute
  '/hall': typeof HallRoute
  '/kept': typeof KeptRoute
  '/library': typeof LibraryRoute
  '/lives': typeof LivesRoute
  '/map': typeof MapRoute
  '/midnight': typeof MidnightRoute
  '/needed': typeof NeededRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/terms': typeof TermsRoute
  '/vault': typeof VaultRoute
  '/voice': typeof VoiceRoute
  '/wall': typeof WallRoute
  '/archive/$id': typeof ArchiveIdRoute
  '/library/$id': typeof LibraryIdRoute
  '/lives/$id': typeof LivesIdRoute
  '/vault/$id': typeof VaultIdRoute
  '/voice/$id': typeof VoiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/curator': typeof CuratorRoute
  '/desk': typeof DeskRoute
  '/exit': typeof ExitRoute
  '/forgotten': typeof ForgottenRoute
  '/guidelines': typeof GuidelinesRoute
  '/hall': typeof HallRoute
  '/kept': typeof KeptRoute
  '/library': typeof LibraryRoute
  '/lives': typeof LivesRoute
  '/map': typeof MapRoute
  '/midnight': typeof MidnightRoute
  '/needed': typeof NeededRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/terms': typeof TermsRoute
  '/vault': typeof VaultRoute
  '/voice': typeof VoiceRoute
  '/wall': typeof WallRoute
  '/archive/$id': typeof ArchiveIdRoute
  '/library/$id': typeof LibraryIdRoute
  '/lives/$id': typeof LivesIdRoute
  '/vault/$id': typeof VaultIdRoute
  '/voice/$id': typeof VoiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/curator': typeof CuratorRoute
  '/desk': typeof DeskRoute
  '/exit': typeof ExitRoute
  '/forgotten': typeof ForgottenRoute
  '/guidelines': typeof GuidelinesRoute
  '/hall': typeof HallRoute
  '/kept': typeof KeptRoute
  '/library': typeof LibraryRoute
  '/lives': typeof LivesRoute
  '/map': typeof MapRoute
  '/midnight': typeof MidnightRoute
  '/needed': typeof NeededRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/terms': typeof TermsRoute
  '/vault': typeof VaultRoute
  '/voice': typeof VoiceRoute
  '/wall': typeof WallRoute
  '/archive_/$id': typeof ArchiveIdRoute
  '/library_/$id': typeof LibraryIdRoute
  '/lives_/$id': typeof LivesIdRoute
  '/vault_/$id': typeof VaultIdRoute
  '/voice_/$id': typeof VoiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/curator'
    | '/desk'
    | '/exit'
    | '/forgotten'
    | '/guidelines'
    | '/hall'
    | '/kept'
    | '/library'
    | '/lives'
    | '/map'
    | '/midnight'
    | '/needed'
    | '/privacy'
    | '/safety'
    | '/terms'
    | '/vault'
    | '/voice'
    | '/wall'
    | '/archive/$id'
    | '/library/$id'
    | '/lives/$id'
    | '/vault/$id'
    | '/voice/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/curator'
    | '/desk'
    | '/exit'
    | '/forgotten'
    | '/guidelines'
    | '/hall'
    | '/kept'
    | '/library'
    | '/lives'
    | '/map'
    | '/midnight'
    | '/needed'
    | '/privacy'
    | '/safety'
    | '/terms'
    | '/vault'
    | '/voice'
    | '/wall'
    | '/archive/$id'
    | '/library/$id'
    | '/lives/$id'
    | '/vault/$id'
    | '/voice/$id'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/curator'
    | '/desk'
    | '/exit'
    | '/forgotten'
    | '/guidelines'
    | '/hall'
    | '/kept'
    | '/library'
    | '/lives'
    | '/map'
    | '/midnight'
    | '/needed'
    | '/privacy'
    | '/safety'
    | '/terms'
    | '/vault'
    | '/voice'
    | '/wall'
    | '/archive_/$id'
    | '/library_/$id'
    | '/lives_/$id'
    | '/vault_/$id'
    | '/voice_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  CuratorRoute: typeof CuratorRoute
  DeskRoute: typeof DeskRoute
  ExitRoute: typeof ExitRoute
  ForgottenRoute: typeof ForgottenRoute
  GuidelinesRoute: typeof GuidelinesRoute
  HallRoute: typeof HallRoute
  KeptRoute: typeof KeptRoute
  LibraryRoute: typeof LibraryRoute
  LivesRoute: typeof LivesRoute
  MapRoute: typeof MapRoute
  MidnightRoute: typeof MidnightRoute
  NeededRoute: typeof NeededRoute
  PrivacyRoute: typeof PrivacyRoute
  SafetyRoute: typeof SafetyRoute
  TermsRoute: typeof TermsRoute
  VaultRoute: typeof VaultRoute
  VoiceRoute: typeof VoiceRoute
  WallRoute: typeof WallRoute
  ArchiveIdRoute: typeof ArchiveIdRoute
  LibraryIdRoute: typeof LibraryIdRoute
  LivesIdRoute: typeof LivesIdRoute
  VaultIdRoute: typeof VaultIdRoute
  VoiceIdRoute: typeof VoiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curator': {
      id: '/curator'
      path: '/curator'
      fullPath: '/curator'
      preLoaderRoute: typeof CuratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exit': {
      id: '/exit'
      path: '/exit'
      fullPath: '/exit'
      preLoaderRoute: typeof ExitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgotten': {
      id: '/forgotten'
      path: '/forgotten'
      fullPath: '/forgotten'
      preLoaderRoute: typeof ForgottenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall': {
      id: '/hall'
      path: '/hall'
      fullPath: '/hall'
      preLoaderRoute: typeof HallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kept': {
      id: '/kept'
      path: '/kept'
      fullPath: '/kept'
      preLoaderRoute: typeof KeptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lives': {
      id: '/lives'
      path: '/lives'
      fullPath: '/lives'
      preLoaderRoute: typeof LivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/midnight': {
      id: '/midnight'
      path: '/midnight'
      fullPath: '/midnight'
      preLoaderRoute: typeof MidnightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/needed': {
      id: '/needed'
      path: '/needed'
      fullPath: '/needed'
      preLoaderRoute: typeof NeededRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wall': {
      id: '/wall'
      path: '/wall'
      fullPath: '/wall'
      preLoaderRoute: typeof WallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive_/$id': {
      id: '/archive_/$id'
      path: '/archive/$id'
      fullPath: '/archive/$id'
      preLoaderRoute: typeof ArchiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library_/$id': {
      id: '/library_/$id'
      path: '/library/$id'
      fullPath: '/library/$id'
      preLoaderRoute: typeof LibraryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lives_/$id': {
      id: '/lives_/$id'
      path: '/lives/$id'
      fullPath: '/lives/$id'
      preLoaderRoute: typeof LivesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault_/$id': {
      id: '/vault_/$id'
      path: '/vault/$id'
      fullPath: '/vault/$id'
      preLoaderRoute: typeof VaultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice_/$id': {
      id: '/voice_/$id'
      path: '/voice/$id'
      fullPath: '/voice/$id'
      preLoaderRoute: typeof VoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  CuratorRoute: CuratorRoute,
  DeskRoute: DeskRoute,
  ExitRoute: ExitRoute,
  ForgottenRoute: ForgottenRoute,
  GuidelinesRoute: GuidelinesRoute,
  HallRoute: HallRoute,
  KeptRoute: KeptRoute,
  LibraryRoute: LibraryRoute,
  LivesRoute: LivesRoute,
  MapRoute: MapRoute,
  MidnightRoute: MidnightRoute,
  NeededRoute: NeededRoute,
  PrivacyRoute: PrivacyRoute,
  SafetyRoute: SafetyRoute,
  TermsRoute: TermsRoute,
  VaultRoute: VaultRoute,
  VoiceRoute: VoiceRoute,
  WallRoute: WallRoute,
  ArchiveIdRoute: ArchiveIdRoute,
  LibraryIdRoute: LibraryIdRoute,
  LivesIdRoute: LivesIdRoute,
  VaultIdRoute: VaultIdRoute,
  VoiceIdRoute: VoiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
